export const ORDER_STATUS = {
  PENDING: "MENUNGGU_KONFIRMASI",
  PROCESSING: "DIPROSES",
  COMPLETED: "SELESAI",
  CANCELLED: "DIBATALKAN",
} as const;

export const ORDER_STATUS_TRANSITIONS: Record<string, string[]> = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};

export const USER_ROLE = {
  BUYER: "buyer",
  SELLER: "seller",
} as const;
